
name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        container:
          image: meterian/cli:latest-gha
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: My custom step
            run: |
              echo "Installing poetry..."
              python3 -m venv /usr/lib/pythonEnvs
              /usr/lib/pythonEnvs/bin/pip install -U pip setuptools
              /usr/lib/pythonEnvs/bin/pip install -U pip poetry
              ln -s /usr/lib/pythonEnvs/bin/poetry /usr/bin/poetry
          - name: Meterian Scanner
            run: meterian_github_action.sh v1.0.17
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN_QA }}
              METERIAN_ENV: qa
              GITHUB_TOKEN: ${{ github.token }}
              INPUT_AUTOFIX_SECURITY: conservative
              INPUT_AUTOFIX_STABILITY: conservative
              INPUT_AUTOFIX_WITH_PR: true
              INPUT_CLI_ARGS: --flags=env=qa --debug
