name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            uses: MeterianHQ/meterian-github-action@v1.0.17
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN_QA }}
              GITHUB_TOKEN: ${{ github.token }}
              METERIAN_ENV: qa
            with:
              autofix_security: conservative
              autofix_stability: conservative
              autofix_with_pr: true
              cli_args: --flags=env=qa
